services:
  vnvc-staff-gateway-api-stag:
    build:
      context: .
      dockerfile: src/VnvcStaffAdmin.Gateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "50003:8080"
    networks:
      - vnvc-staff
    depends_on:
      - database-mongodb

  vnvc-staff-auth-api-stag:
    build:
      context: .
      dockerfile: src/VnvcStaffAdmin.Authen/Dockerfile
    ports:
      - "50005:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Docker
      - MONGO_ADMINSTAFF_CONNECTION_STRING=mongodb://database-mongodb:27017
      - IDENTITY_MONGODB_DATABASE_NAME=identity
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mypass
      - ES_HOST=localhost
      - ES_PORT=9200
    networks:
      - vnvc-staff
    depends_on:
      - database-mongodb

  vnvc-staff-staff-api-stag:
    build:
      context: .
      dockerfile: src/VnvcStaffAdmin.WebApi/Dockerfile
    ports:
      - "50000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Docker
      - MONGO_ADMINSTAFF_CONNECTION_STRING=mongodb://database-mongodb:27017
      - IDENTITY_MONGODB_DATABASE_NAME=identity
      - ADMIN_STAFF_MONGODB_DATABASE_NAME=admin_staff
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mypass
      - ES_HOST=localhost
      - ES_PORT=9200
      - ES_USER_NAME=example,
      - ES_PASSWORD=example,
      - S3_MINIO_ENDPOINT=example
      - S3_MINIO_ACCESSKEY=example
      - S3_MINIO_SECRETKEY=example
      - S3_MINIO_BUCKETNAME=example
      - S3_MINIO_REGION=example
    networks:
      - vnvc-staff
    depends_on:
      - database-mongodb

  database-mongodb:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - vnvc-staff

volumes:
  mongodb_data:

networks:
  vnvc-staff:
    external: true