<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.15.9" />
    <PackageReference Include="Elasticsearch.Net" Version="7.17.5" />
    <PackageReference Include="EPPlus" Version="7.3.2" />
    <PackageReference Include="libphonenumber-csharp" Version="8.13.46" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    <PackageReference Include="Minio" Version="6.0.3" />
    <PackageReference Include="NEST" Version="7.17.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VnvcStaffAdmin.Infrastructure\VnvcStaffAdmin.Infrastructure.csproj" />
  </ItemGroup>

</Project>
