# CI/CD Workflow for STAFF_ADMIN with Docker and Harbor
name: CI/CD for STAFF_ADMIN

on:
  push:
    branches: [staging, production, khoadna/main/init_project]
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "VnvcStaffAdmin.Application.csproj"
  pull_request:
    branches: [staging, production, khoadna/main/init_project]
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "VnvcStaffAdmin.Application.csproj"

env:
  DOCKERCOMPOSE_FILE: 'docker-compose.yml'

jobs:
  docker-build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - VnvcStaffAdmin.Authen
          - VnvcStaffAdmin.Gateway
          - VnvcStaffAdmin.WebApi
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Sử dụng phiên bản mới hoặc mặc định

      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Ho_Chi_Minh"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure build variables
        id: config
        run: |
          echo "SERVICE_NAME=${{ matrix.service }}" >> $GITHUB_ENV
          echo "URL_NAME=$(echo "eplusapp/${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "VERSION_TAG=v$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Log in to Harbor registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build / push ${{ matrix.service }}
        uses: docker/build-push-action@v6 # Sử dụng phiên bản v5 mới nhất
        with:
          context: .
          file: src/${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ env.URL_NAME }}:${{ env.VERSION_TAG }}
          build-args: |
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            GIT_SHA=${GITHUB_SHA}

  deploy:
    name: Deploy to Environment
    needs: docker-build
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/production' && 'production' || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set deployment environment
        id: deploy_env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            echo "env=production" >> $GITHUB_ENV
          else
            echo "env=staging" >> $GITHUB_ENV
          fi
          echo "VERSION_TAG=v$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Deploy to environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets[format('{0}_HOST', env.env)] }}
          username: ${{ secrets[format('{0}_USER', env.env)] }}
          key: ${{ secrets[format('{0}_SSH_PRIVATE_KEY', env.env)] }}
          port: ${{ secrets[format('{0}_SSH_PORT_1', env.env)] }}

          command_timeout: "10m"
          script: |
            for service in VnvcStaffAdmin.WebApi VnvcStaffAdmin.Authen VnvcStaffAdmin.Gateway; do
              url_name=$(echo "eplusapp/${service}" | tr '[:upper:]' '[:lower:]')
              sed -i "s|image: ${{ secrets.REGISTRY_URL }}/${url_name}:.*|image: ${{ secrets.REGISTRY_URL }}/${url_name}:${{ env.VERSION_TAG }}|g" ${{ env.DOCKERCOMPOSE_FILE }}
            done

            docker compose -f ${{ env.DOCKERCOMPOSE_FILE }} pull
            docker compose -f ${{ env.DOCKERCOMPOSE_FILE }} up -d

            docker system prune -f --volumes
